name: libjuice-hs
version: '0.0.0'
synopsis: An example project
description: An example project
maintainer: Philipp Balzarek

extra-libraries:
  - pthread
include-dirs: libjuice/include/juice
c-sources:
  - libjuice/src/*.c
cc-options:
  - -O2
  - -DNO_SERVER
  - -fPIC
  - -pthread
  - -Wno-address-of-packed-member
extra-source-files:
  - libjuice/include/**/*.h

dependencies:
  - base
  - aeson
  - async
  - bytestring
  - containers
  - data-default
  - lens
  - mtl
  - text
  - inline-c
  - exceptions

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Werror=incomplete-uni-patterns
    - -Werror=incomplete-record-updates

library:
  dependencies:
  - base
  source-dirs: src
  exposed-modules:
    - LibJuice

tests:
  tests:
    dependencies:
    - libjuice-hs
    - hedgehog
    - tasty
    - tasty-hedgehog
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
